server:
   port: 9000

spring:
   application:
      name: sq-config
   cloud:
      config:
         server:
            git:
               default-label: main
               uri: https://github.com/S3-CloudConfig/SqConfig/
               search-paths: /config
               username:
               password:

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka


